import { createFileRoute } from "@tanstack/react-router";
import { AppLayout } from "@/components/layout/AppLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Clock } from "lucide-react";

export const Route = createFileRoute("/study-plan")({
  head: () => ({
    meta: [
      { title: "Study Plan — StudyAI" },
      { name: "description", content: "Your personalized weekly study plan generated by AI." },
      { property: "og:title", content: "Study Plan — StudyAI" },
      { property: "og:description", content: "Personalized study plan." },
    ],
  }),
  component: StudyPlanPage,
});

const week = [
  {
    day: "Monday",
    date: "Nov 4",
    tasks: [
      { time: "4:00 PM", title: "Read Cell Biology Ch. 5", tag: "Biology", done: true },
      { time: "6:00 PM", title: "Flashcards: Organelles", tag: "Flashcards", done: true },
    ],
  },
  {
    day: "Tuesday",
    date: "Nov 5",
    tasks: [
      { time: "3:30 PM", title: "Practice: Derivatives", tag: "Calculus", done: false },
      { time: "7:00 PM", title: "Quiz: Membrane Transport", tag: "Biology", done: false },
    ],
  },
  {
    day: "Wednesday",
    date: "Nov 6",
    tasks: [
      { time: "5:00 PM", title: "Summary review: WWII", tag: "History", done: false },
    ],
  },
  {
    day: "Thursday",
    date: "Nov 7",
    tasks: [
      { time: "4:30 PM", title: "Chem lab prep", tag: "Chemistry", done: false },
      { time: "8:00 PM", title: "Flashcards: Verbs (Spanish)", tag: "Language", done: false },
    ],
  },
  {
    day: "Friday",
    date: "Nov 8",
    tasks: [
      { time: "3:00 PM", title: "Weekly review session", tag: "Review", done: false },
    ],
  },
];

function StudyPlanPage() {
  return (
    <AppLayout title="Study plan" subtitle="This week · Nov 4 – Nov 10">
      <div className="grid gap-4 lg:grid-cols-2">
        {week.map((d) => (
          <Card key={d.day} className="rounded-2xl border-border shadow-[var(--shadow-soft)]">
            <CardHeader className="flex-row items-center justify-between">
              <div>
                <CardTitle className="text-base font-semibold">{d.day}</CardTitle>
                <p className="text-xs text-muted-foreground">{d.date}</p>
              </div>
              <Badge variant="secondary" className="rounded-full">{d.tasks.length} tasks</Badge>
            </CardHeader>
            <CardContent className="space-y-2">
              {d.tasks.map((t) => (
                <label
                  key={t.title}
                  className="flex items-center gap-3 rounded-xl border border-border bg-background p-3 transition hover:bg-accent/40"
                >
                  <Checkbox defaultChecked={t.done} className="rounded" />
                  <div className="min-w-0 flex-1">
                    <p className={`truncate text-sm font-medium ${t.done ? "line-through text-muted-foreground" : ""}`}>
                      {t.title}
                    </p>
                    <p className="mt-0.5 flex items-center gap-1 text-xs text-muted-foreground">
                      <Clock className="h-3 w-3" /> {t.time}
                    </p>
                  </div>
                  <Badge variant="outline" className="shrink-0 rounded-full text-xs">{t.tag}</Badge>
                </label>
              ))}
            </CardContent>
          </Card>
        ))}
      </div>
    </AppLayout>
  );
}
